### ISSUE TITLE
New framework

### ISSUE THREAD

**Issue by Yomanz** [1Computer1/discord.js-frameworks-comparison#8]
Hola i'm working on a new framework but it's in eris. Is that something that could be added to the list or is it strictly discord.js frameworks. 
Thanks,

**Comment by zajrik** [comment]
Of course this is strictly limited to Discord.js frameworks. The title is literally `discord.js-frameworks-comparison`. Good luck with your new framework though. You're in for a lot of labor, speaking from experience. 🤣

**Comment by Yomanz** [comment]
Cheers 🤣🤣
